# Generated by Django 5.0.3 on 2024-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
    ]
