# Generated by Django 5.0.3 on 2024-03-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_rename_staffs_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackStaffs',
            new_name='FeedBackStaff',
        ),
    ]
