# Generated by Django 5.0.3 on 2024-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_rename_feedbackstaffs_feedbackstaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationStaffs',
            new_name='NotificationStaff',
        ),
    ]
